export interface TimezoneOption {
  value: string;
  label: string;
}

export interface TimezoneGroup {
  group: string;
  zones: TimezoneOption[];
}

// Shown at top of dropdown — US + Ecuador priority
export const PRIORITY_TIMEZONES: TimezoneOption[] = [
  { value: 'America/New_York',    label: 'US Eastern (New York)' },
  { value: 'America/Chicago',     label: 'US Central (Chicago)' },
  { value: 'America/Denver',      label: 'US Mountain (Denver)' },
  { value: 'America/Phoenix',     label: 'US Mountain – No DST (Phoenix)' },
  { value: 'America/Los_Angeles', label: 'US Pacific (Los Angeles)' },
  { value: 'America/Anchorage',   label: 'US Alaska (Anchorage)' },
  { value: 'America/Honolulu',    label: 'US Hawaii (Honolulu)' },
  { value: 'America/Guayaquil',   label: 'Ecuador (Guayaquil)' },
];

export const TIMEZONE_GROUPS: TimezoneGroup[] = [
  {
    group: 'United States',
    zones: [
      { value: 'America/New_York',         label: 'Eastern (New York)' },
      { value: 'America/Detroit',          label: 'Eastern – Michigan (Detroit)' },
      { value: 'America/Indiana/Indianapolis', label: 'Eastern – Indiana (Indianapolis)' },
      { value: 'America/Chicago',          label: 'Central (Chicago)' },
      { value: 'America/Indiana/Knox',     label: 'Central – Indiana (Knox)' },
      { value: 'America/Menominee',        label: 'Central – Michigan (Menominee)' },
      { value: 'America/Denver',           label: 'Mountain (Denver)' },
      { value: 'America/Phoenix',          label: 'Mountain – No DST (Phoenix)' },
      { value: 'America/Boise',            label: 'Mountain – Idaho (Boise)' },
      { value: 'America/Los_Angeles',      label: 'Pacific (Los Angeles)' },
      { value: 'America/Anchorage',        label: 'Alaska (Anchorage)' },
      { value: 'America/Juneau',           label: 'Alaska – Juneau' },
      { value: 'America/Nome',             label: 'Alaska – Nome' },
      { value: 'America/Adak',             label: 'Hawaii-Aleutian – Adak' },
      { value: 'America/Honolulu',         label: 'Hawaii (Honolulu)' },
      { value: 'Pacific/Pago_Pago',        label: 'American Samoa' },
      { value: 'Pacific/Guam',             label: 'Guam / Chamorro' },
      { value: 'America/Puerto_Rico',      label: 'Puerto Rico / US Virgin Islands' },
    ],
  },
  {
    group: 'Canada',
    zones: [
      { value: 'America/St_Johns',       label: 'Newfoundland (St. John\'s)' },
      { value: 'America/Halifax',        label: 'Atlantic (Halifax)' },
      { value: 'America/Toronto',        label: 'Eastern (Toronto)' },
      { value: 'America/Winnipeg',       label: 'Central (Winnipeg)' },
      { value: 'America/Regina',         label: 'Central – No DST (Regina)' },
      { value: 'America/Edmonton',       label: 'Mountain (Edmonton)' },
      { value: 'America/Vancouver',      label: 'Pacific (Vancouver)' },
      { value: 'America/Whitehorse',     label: 'Yukon (Whitehorse)' },
    ],
  },
  {
    group: 'Mexico & Central America',
    zones: [
      { value: 'America/Mexico_City',    label: 'Central (Mexico City)' },
      { value: 'America/Cancun',         label: 'Eastern – No DST (Cancún)' },
      { value: 'America/Monterrey',      label: 'Central (Monterrey)' },
      { value: 'America/Chihuahua',      label: 'Mountain (Chihuahua)' },
      { value: 'America/Tijuana',        label: 'Pacific (Tijuana)' },
      { value: 'America/Guatemala',      label: 'Guatemala' },
      { value: 'America/Tegucigalpa',    label: 'Honduras (Tegucigalpa)' },
      { value: 'America/Managua',        label: 'Nicaragua (Managua)' },
      { value: 'America/Costa_Rica',     label: 'Costa Rica' },
      { value: 'America/Panama',         label: 'Panama' },
      { value: 'America/El_Salvador',    label: 'El Salvador' },
    ],
  },
  {
    group: 'Caribbean',
    zones: [
      { value: 'America/Havana',         label: 'Cuba (Havana)' },
      { value: 'America/Jamaica',        label: 'Jamaica' },
      { value: 'America/Santo_Domingo',  label: 'Dominican Republic' },
      { value: 'America/Port-au-Prince', label: 'Haiti' },
      { value: 'America/Barbados',       label: 'Barbados' },
      { value: 'America/Trinidad',       label: 'Trinidad & Tobago' },
    ],
  },
  {
    group: 'South America',
    zones: [
      { value: 'America/Guayaquil',      label: 'Ecuador (Guayaquil)' },
      { value: 'America/Bogota',         label: 'Colombia (Bogotá)' },
      { value: 'America/Lima',           label: 'Peru (Lima)' },
      { value: 'America/Caracas',        label: 'Venezuela (Caracas)' },
      { value: 'America/La_Paz',         label: 'Bolivia (La Paz)' },
      { value: 'America/Santiago',       label: 'Chile (Santiago)' },
      { value: 'America/Asuncion',       label: 'Paraguay (Asunción)' },
      { value: 'America/Argentina/Buenos_Aires', label: 'Argentina (Buenos Aires)' },
      { value: 'America/Montevideo',     label: 'Uruguay (Montevideo)' },
      { value: 'America/Sao_Paulo',      label: 'Brazil – São Paulo' },
      { value: 'America/Manaus',         label: 'Brazil – Manaus' },
      { value: 'America/Belem',          label: 'Brazil – Belém' },
      { value: 'America/Fortaleza',      label: 'Brazil – Fortaleza' },
      { value: 'America/Recife',         label: 'Brazil – Recife' },
      { value: 'America/Noronha',        label: 'Brazil – Fernando de Noronha' },
      { value: 'America/Cayenne',        label: 'French Guiana (Cayenne)' },
      { value: 'America/Paramaribo',     label: 'Suriname (Paramaribo)' },
      { value: 'America/Guyana',         label: 'Guyana (Georgetown)' },
    ],
  },
  {
    group: 'Europe',
    zones: [
      { value: 'Europe/London',          label: 'UK (London / GMT)' },
      { value: 'Europe/Dublin',          label: 'Ireland (Dublin)' },
      { value: 'Europe/Lisbon',          label: 'Portugal (Lisbon)' },
      { value: 'Atlantic/Canary',        label: 'Canary Islands' },
      { value: 'Europe/Paris',           label: 'France (Paris / CET)' },
      { value: 'Europe/Berlin',          label: 'Germany (Berlin)' },
      { value: 'Europe/Amsterdam',       label: 'Netherlands (Amsterdam)' },
      { value: 'Europe/Brussels',        label: 'Belgium (Brussels)' },
      { value: 'Europe/Madrid',          label: 'Spain (Madrid)' },
      { value: 'Europe/Rome',            label: 'Italy (Rome)' },
      { value: 'Europe/Zurich',          label: 'Switzerland (Zurich)' },
      { value: 'Europe/Vienna',          label: 'Austria (Vienna)' },
      { value: 'Europe/Warsaw',          label: 'Poland (Warsaw)' },
      { value: 'Europe/Prague',          label: 'Czech Republic (Prague)' },
      { value: 'Europe/Stockholm',       label: 'Sweden (Stockholm)' },
      { value: 'Europe/Oslo',            label: 'Norway (Oslo)' },
      { value: 'Europe/Copenhagen',      label: 'Denmark (Copenhagen)' },
      { value: 'Europe/Helsinki',        label: 'Finland (Helsinki)' },
      { value: 'Europe/Athens',          label: 'Greece (Athens)' },
      { value: 'Europe/Bucharest',       label: 'Romania (Bucharest)' },
      { value: 'Europe/Budapest',        label: 'Hungary (Budapest)' },
      { value: 'Europe/Kiev',            label: 'Ukraine (Kyiv)' },
      { value: 'Europe/Moscow',          label: 'Russia (Moscow)' },
      { value: 'Europe/Istanbul',        label: 'Turkey (Istanbul)' },
    ],
  },
  {
    group: 'Africa',
    zones: [
      { value: 'Africa/Abidjan',         label: 'West Africa – No DST (Abidjan)' },
      { value: 'Africa/Lagos',           label: 'Nigeria (Lagos / WAT)' },
      { value: 'Africa/Casablanca',      label: 'Morocco (Casablanca)' },
      { value: 'Africa/Cairo',           label: 'Egypt (Cairo / EET)' },
      { value: 'Africa/Nairobi',         label: 'Kenya (Nairobi / EAT)' },
      { value: 'Africa/Johannesburg',    label: 'South Africa (Johannesburg / SAST)' },
      { value: 'Africa/Addis_Ababa',     label: 'Ethiopia (Addis Ababa)' },
      { value: 'Africa/Dar_es_Salaam',   label: 'Tanzania (Dar es Salaam)' },
      { value: 'Africa/Accra',           label: 'Ghana (Accra)' },
      { value: 'Africa/Khartoum',        label: 'Sudan (Khartoum)' },
    ],
  },
  {
    group: 'Middle East',
    zones: [
      { value: 'Asia/Dubai',             label: 'UAE (Dubai / GST)' },
      { value: 'Asia/Riyadh',            label: 'Saudi Arabia (Riyadh / AST)' },
      { value: 'Asia/Kuwait',            label: 'Kuwait' },
      { value: 'Asia/Qatar',             label: 'Qatar (Doha)' },
      { value: 'Asia/Bahrain',           label: 'Bahrain' },
      { value: 'Asia/Muscat',            label: 'Oman (Muscat)' },
      { value: 'Asia/Baghdad',           label: 'Iraq (Baghdad)' },
      { value: 'Asia/Tehran',            label: 'Iran (Tehran / IRST)' },
      { value: 'Asia/Jerusalem',         label: 'Israel (Jerusalem)' },
      { value: 'Asia/Beirut',            label: 'Lebanon (Beirut)' },
      { value: 'Asia/Amman',             label: 'Jordan (Amman)' },
    ],
  },
  {
    group: 'South & Central Asia',
    zones: [
      { value: 'Asia/Karachi',           label: 'Pakistan (Karachi / PKT)' },
      { value: 'Asia/Kolkata',           label: 'India (IST)' },
      { value: 'Asia/Colombo',           label: 'Sri Lanka (Colombo)' },
      { value: 'Asia/Dhaka',             label: 'Bangladesh (Dhaka / BST)' },
      { value: 'Asia/Kathmandu',         label: 'Nepal (Kathmandu / NPT)' },
      { value: 'Asia/Tashkent',          label: 'Uzbekistan (Tashkent)' },
      { value: 'Asia/Almaty',            label: 'Kazakhstan (Almaty)' },
      { value: 'Asia/Kabul',             label: 'Afghanistan (Kabul / AFT)' },
    ],
  },
  {
    group: 'East & Southeast Asia',
    zones: [
      { value: 'Asia/Shanghai',          label: 'China (Shanghai / CST)' },
      { value: 'Asia/Hong_Kong',         label: 'Hong Kong (HKT)' },
      { value: 'Asia/Taipei',            label: 'Taiwan (Taipei / CST)' },
      { value: 'Asia/Tokyo',             label: 'Japan (Tokyo / JST)' },
      { value: 'Asia/Seoul',             label: 'South Korea (Seoul / KST)' },
      { value: 'Asia/Singapore',         label: 'Singapore (SGT)' },
      { value: 'Asia/Kuala_Lumpur',      label: 'Malaysia (Kuala Lumpur / MYT)' },
      { value: 'Asia/Bangkok',           label: 'Thailand (Bangkok / ICT)' },
      { value: 'Asia/Jakarta',           label: 'Indonesia – West (Jakarta / WIB)' },
      { value: 'Asia/Makassar',          label: 'Indonesia – Central (Makassar / WITA)' },
      { value: 'Asia/Jayapura',          label: 'Indonesia – East (Jayapura / WIT)' },
      { value: 'Asia/Manila',            label: 'Philippines (Manila / PHT)' },
      { value: 'Asia/Ho_Chi_Minh',       label: 'Vietnam (Ho Chi Minh / ICT)' },
      { value: 'Asia/Rangoon',           label: 'Myanmar (Yangon / MMT)' },
      { value: 'Asia/Ulaanbaatar',       label: 'Mongolia (Ulaanbaatar)' },
    ],
  },
  {
    group: 'Australia & Pacific',
    zones: [
      { value: 'Australia/Perth',        label: 'Australia – Western (Perth / AWST)' },
      { value: 'Australia/Darwin',       label: 'Australia – Northern (Darwin / ACST)' },
      { value: 'Australia/Adelaide',     label: 'Australia – Central (Adelaide / ACST)' },
      { value: 'Australia/Brisbane',     label: 'Australia – Queensland (Brisbane / AEST)' },
      { value: 'Australia/Sydney',       label: 'Australia – Eastern (Sydney / AEST)' },
      { value: 'Australia/Melbourne',    label: 'Australia – Victoria (Melbourne / AEST)' },
      { value: 'Australia/Hobart',       label: 'Australia – Tasmania (Hobart)' },
      { value: 'Pacific/Auckland',       label: 'New Zealand (Auckland / NZST)' },
      { value: 'Pacific/Fiji',           label: 'Fiji' },
      { value: 'Pacific/Tahiti',         label: 'French Polynesia (Tahiti)' },
      { value: 'Pacific/Honolulu',       label: 'Hawaii (Honolulu / HST)' },
    ],
  },
  {
    group: 'UTC / Other',
    zones: [
      { value: 'UTC',                    label: 'UTC (Coordinated Universal Time)' },
      { value: 'Etc/GMT+12',             label: 'UTC−12' },
      { value: 'Etc/GMT+11',             label: 'UTC−11' },
      { value: 'Etc/GMT-1',             label: 'UTC+1' },
      { value: 'Etc/GMT-5',             label: 'UTC+5' },
    ],
  },
];
